### PR TITLE
feat(earnings model): initialise funder field based on org_name instead of name field

### PR DESCRIPTION
**Pull request by Mloweedgar**

### CODE REVIEW

**Comment by dadiorchen** [comment]
@Mloweedgar to solve these failing tests. Please mock the API for the upstream API/service. like the stakeholder.

This is an example:
https://github.com/Greenstand/treetracker-messaging-api/blob/27277890d48369aaa6ca439c54dd1f7a1523fb76/api-tests/message-api.spec.js#L9-L29

**Comment by dadiorchen** [comment]
So in this way, we don't rely on external factors to build our API

**Comment by dadiorchen** [comment]
Is there any trouble mocking the api? @Mloweedgar

**Comment by dadiorchen** [comment]
@Mloweedgar I will merge this first, when you finished the mock please raise a PR again

**Comment by Mloweedgar** [comment]
Okay @dadiorchen, I will do that, currently I am working to make tests run in my locally computer after that I will mock the api

**Pull request merged**
